FROM jenkins/jenkins:lts
COPY integration-test/metrics.groovy /usr/share/jenkins/ref/init.groovy.d/metrics.groovy
RUN /usr/local/bin/install-plugins.sh docker-slaves metrics cloudbees-folder

ARG PORT

ENV JENKINS_OPTS --httpPort=${PORT}
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
