FROM quay.io/signalfuse/collectd:latest

# Disable everything we can except elasticsearch
ENV COLLECTD_INTERVAL=3 COLLECTD_HOSTNAME=jenkins-test DISABLE_AGGREGATION=true DISABLE_CPU=true DISABLE_CPUFREQ=true DISABLE_DF=true DISABLE_DISK=true DISABLE_DOCKER=true DISABLE_HOST_MONITORING=true DISABLE_INTERFACE=true DISABLE_LOAD=true DISABLE_MEMORY=true DISABLE_PROTOCOLS=true DISABLE_VMEM=true DISABLE_UPTIME=true

# Debian is super minimalistic
RUN apt-get update &&\
    apt-get install -yq netcat curl

CMD /.docker/setup_jenkins
ADD integration-test/setup_jenkins /.docker/setup_jenkins

## The context of the image build should be the root dir of this repo!!
ADD jenkins.py /opt/collectd-jenkins/
ADD urllib_auth_n_ssl_handler.py /opt/collectd-jenkins/
ADD integration-test/20-jenkins-test.conf /etc/collectd/managed_config/
