name: Integration Test

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']
    branches:
      - main
  pull_request:

env:
  PYTHON_VERSION: "3.8"
  REQUIREMENTS_PATH: "test_requirements.txt"

jobs:
  integration-test:
    name: integration-test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
          key: v1-pytest-${{ env.PYTHON_VERSION }}-${{ hashFiles(env.REQUIREMENTS_PATH) }}

      - name: Install dependencies
        run: pip install -r "${{ env.REQUIREMENTS_PATH }}"

      - name: Run tests
        working-directory: integration-test
        run: bash run.sh
